# Data Understanding

![Alternative Text](image.png)

In [1]:
# Import Necessary Libraries

In [2]:
import numpy as np
import pandas as pd
import plotly.express as px

In [3]:
import warnings
warnings.filterwarnings('ignore')

# Load Data

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
df = pd.read_csv('Downloads/car_insurance_claim.csv', index_col= 0)
df.head()

,KIDSDRIV,BIRTH,AGE,HOMEKIDS,YOJ,INCOME,PARENT1,HOME_VAL,MSTATUS,GENDER,EDUCATION,OCCUPATION,TRAVTIME,CAR_USE,BLUEBOOK,TIF,CAR_TYPE,RED_CAR,OLDCLAIM,CLM_FREQ,REVOKED,MVR_PTS,CLM_AMT,CAR_AGE,CLAIM_FLAG,URBANICITY
ID,,,,,,,,,,,,,,,,,,,,,,,,,,
63581743,0,16-Mar-39,60.0,0,11.0,"$67,349",No,$0,z_No,M,PhD,Professional,14,Private,"$14,230",11,Minivan,yes,"$4,461",2,No,3,$0,18.0,0,Highly Urban/ Urban
132761049,0,21-Jan-56,43.0,0,11.0,"$91,449",No,"$257,252",z_No,M,z_High School,z_Blue Collar,22,Commercial,"$14,940",1,Minivan,yes,$0,0,No,0,$0,1.0,0,Highly Urban/ Urban
921317019,0,18-Nov-51,48.0,0,11.0,"$52,881",No,$0,z_No,M,Bachelors,Manager,26,Private,"$21,970",1,Van,yes,$0,0,No,2,$0,10.0,0,Highly Urban/ Urban
727598473,0,05-Mar-64,35.0,1,10.0,"$16,039",No,"$124,191",Yes,z_F,z_High School,Clerical,5,Private,"$4,010",4,z_SUV,no,"$38,690",2,No,3,$0,10.0,0,Highly Urban/ Urban
450221861,0,05-Jun-48,51.0,0,14.0,NaN,No,"$306,251",Yes,M,<High School,z_Blue Collar,32,Private,"$15,440",7,Minivan,yes,$0,0,No,0,$0,6.0,0,Highly Urban/ Urban

# Data Cleaning step

### 1 - check Data Types

In [6]:
# Check Data Types
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10302 entries, 63581743 to 680381960
Data columns (total 26 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   KIDSDRIV    10302 non-null  int64
 1   BIRTH       10302 non-null  object
 2   AGE         10295 non-null  float64
 3   HOMEKIDS    10302 non-null  int64
 4   YOJ         9754 non-null   float64
 5   INCOME      9732 non-null   object
 6   PARENT1     10302 non-null  object
 7   HOME_VAL    9727 non-null   object
 8   MSTATUS     10302 non-null  object
 9   GENDER      10302 non-null  object
 10  EDUCATION   10302 non-null  object
 11  OCCUPATION  9637 non-null   object
 12  TRAVTIME    10302 non-null  int64
 13  CAR_USE     10302 non-null  object
 14  BLUEBOOK    10302 non-null  object
 15  TIF         10302 non-null  int64
 16  CAR_TYPE    10302 non-null  object
 17  RED_CAR     10302 non-null  object
 18  OLDCLAIM    10302 non-null  object
 19  CLM_FREQ    10302 non-null  int64
 20  REVOKED     10302 non-null  object
 21  MVR_PTS     10302 non-null  int64
 22  CLM_AMT     10302 non-null  object
 23  CAR_AGE     9663 non-null   float64
 24  CLAIM_FLAG  10302 non-null  int64
 25  URBANICITY  10302 non-null  object
dtypes: float64(3), int64(7), object(16)
memory usage: 2.1+ MB

### 2 - Check Missing values

In [7]:
# Check missing values
df.isna().sum()

KIDSDRIV        0
BIRTH           0
AGE             7
HOMEKIDS        0
YOJ           548
INCOME        570
PARENT1         0
HOME_VAL      575
MSTATUS         0
GENDER          0
EDUCATION       0
OCCUPATION    665
TRAVTIME        0
CAR_USE         0
BLUEBOOK        0
TIF             0
CAR_TYPE        0
RED_CAR         0
OLDCLAIM        0
CLM_FREQ        0
REVOKED         0
MVR_PTS         0
CLM_AMT         0
CAR_AGE       639
CLAIM_FLAG      0
URBANICITY      0
dtype: int64

In [8]:
df.dropna()

,KIDSDRIV,BIRTH,AGE,HOMEKIDS,YOJ,INCOME,PARENT1,HOME_VAL,MSTATUS,GENDER,EDUCATION,OCCUPATION,TRAVTIME,CAR_USE,BLUEBOOK,TIF,CAR_TYPE,RED_CAR,OLDCLAIM,CLM_FREQ,REVOKED,MVR_PTS,CLM_AMT,CAR_AGE,CLAIM_FLAG,URBANICITY
ID,,,,,,,,,,,,,,,,,,,,,,,,,,
63581743,0,16-Mar-39,60.0,0,11.0,"$67,349",No,$0,z_No,M,PhD,Professional,14,Private,"$14,230",11,Minivan,yes,"$4,461",2,No,3,$0,18.0,0,Highly Urban/ Urban
132761049,0,21-Jan-56,43.0,0,11.0,"$91,449",No,"$257,252",z_No,M,z_High School,z_Blue Collar,22,Commercial,"$14,940",1,Minivan,yes,$0,0,No,0,$0,1.0,0,Highly Urban/ Urban
921317019,0,18-Nov-51,48.0,0,11.0,"$52,881",No,$0,z_No,M,Bachelors,Manager,26,Private,"$21,970",1,Van,yes,$0,0,No,2,$0,10.0,0,Highly Urban/ Urban
727598473,0,05-Mar-64,35.0,1,10.0,"$16,039",No,"$124,191",Yes,z_F,z_High School,Clerical,5,Private,"$4,010",4,z_SUV,no,"$38,690",2,No,3,$0,10.0,0,Highly Urban/ Urban
871024631,0,05-May-65,34.0,1,12.0,"$125,301",Yes,$0,z_No,z_F,Bachelors,z_Blue Collar,46,Commercial,"$17,430",1,Sports Car,no,$0,0,No,0,"$2,946",7.0,1,Highly Urban/ Urban
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121441578,0,01-Jul-64,35.0,0,11.0,"$43,112",No,$0,z_No,M,z_High School,z_Blue Collar,51,Commercial,"$27,330",10,Panel Truck,yes,$0,0,No,0,$0,8.0,0,z_Highly Rural/ Rural
67790126,1,13-Aug-54,45.0,2,9.0,"$164,669",No,"$386,273",Yes,M,PhD,Manager,21,Private,"$13,270",15,Minivan,no,$0,0,No,2,$0,17.0,0,Highly Urban/ Urban
849208064,0,18-Jun-51,48.0,0,15.0,"$39,837",No,"$170,611",Yes,z_F,<High School,z_Blue Collar,12,Private,"$13,820",7,z_SUV,no,$0,0,No,0,$0,1.0,0,Highly Urban/ Urban
627828331,0,12-Dec-48,50.0,0,7.0,"$43,445",No,"$149,248",Yes,z_F,Bachelors,Home Maker,36,Private,"$22,550",6,Minivan,no,$0,0,No,0,$0,11.0,0,Highly Urban/ Urban
680381960,0,27-Feb-47,52.0,0,11.0,"$53,235",No,"$197,017",Yes,z_F,z_High School,Clerical,64,Private,"$19,400",6,Minivan,no,$0,0,No,0,$0,9.0,0,z_Highly Rural/ Rural

In [9]:
round((df.isna().mean()) * 100, 2)

KIDSDRIV      0.00
BIRTH         0.00
AGE           0.07
HOMEKIDS      0.00
YOJ           5.32
INCOME        5.53
PARENT1       0.00
HOME_VAL      5.58
MSTATUS       0.00
GENDER        0.00
EDUCATION     0.00
OCCUPATION    6.46
TRAVTIME      0.00
CAR_USE       0.00
BLUEBOOK      0.00
TIF           0.00
CAR_TYPE      0.00
RED_CAR       0.00
OLDCLAIM      0.00
CLM_FREQ      0.00
REVOKED       0.00
MVR_PTS       0.00
CLM_AMT       0.00
CAR_AGE       6.20
CLAIM_FLAG    0.00
URBANICITY    0.00
dtype: float64

In [10]:
df.dropna(subset= 'AGE', inplace= True, ignore_index= True)
# df.reset_index(inplace= True, drop= True)

### 3 - Check Duplicates

In [11]:
# Check duplicates
df.duplicated().sum()

1

In [12]:
df.drop_duplicates(inplace= True, ignore_index= True)

### 4 - Check Outliers

In [13]:
from datasist.structdata import detect_outliers
numeric_lst = df.select_dtypes(include = 'number').columns.drop('CLAIM_FLAG')
for col in numeric_lst :
    outliers = detect_outliers(data = df , n = 0 , features = [col])
    print(col)
    print(outliers)
    print('-'*50)

KIDSDRIV
[8, 10, 28, 33, 38, 62, 66, 69, 73, 75, 76, 85, 88, 106, 114, 117, 125, 129, 135, 137, 141, 155, 157, 167, 178, 185, 202, 205, 208, 224, 227, 247, 254, 269, 271, 274, 277, 278, 280, 292, 293, 310, 311, 312, 313, 314, 325, 361, 368, 373, 388, 401, 406, 417, 423, 427, 432, 443, 461, 467, 469, 473, 480, 493, 494, 495, 509, 512, 517, 518, 531, 543, 557, 571, 575, 580, 590, 596, 603, 607, 632, 635, 636, 637, 639, 653, 657, 686, 697, 714, 719, 725, 728, 740, 741, 744, 763, 766, 776, 778, 780, 798, 802, 804, 829, 833, 838, 839, 843, 852, 900, 908, 914, 916, 921, 925, 926, 929, 949, 950, 953, 969, 974, 978, 980, 996, 997, 1002, 1007, 1011, 1023, 1025, 1031, 1077, 1083, 1111, 1117, 1143, 1145, 1146, 1160, 1181, 1183, 1189, 1193, 1195, 1203, 1220, 1229, 1232, 1239, 1249, 1255, 1257, 1280, 1319, 1323, 1339, 1341, 1346, 1349, 1362, 1386, 1390, 1398, 1403, 1408, 1416, 1417, 1422, 1432, 1434, 1441, 1457, 1459, 1476, 1480, 1495, 1502, 1503, 1535, 1536, 1540, 1554, 1574, 1601, 1611, 1613, 1638, 1645, 1653, 1665, 1668, 1705, 1706, 1707, 1717, 1720, 1721, 1726, 1739, 1748, 1769, 1786, 1796, 1818, 1825, 1827, 1830, 1838, 1839, 1844, 1848, 1858, 1861, 1874, 1879, 1882, 1891, 1894, 1906, 1907, 1908, 1914, 1921, 1927, 1933, 1953, 1966, 1968, 1980, 1995, 2023, 2025, 2030, 2031, 2047, 2062, 2070, 2074, 2095, 2096, 2100, 2117, 2127, 2137, 2139, 2142, 2143, 2145, 2154, 2156, 2161, 2179, 2185, 2186, 2188, 2202, 2205, 2222, 2236, 2238, 2253, 2259, 2269, 2278, 2280, 2286, 2290, 2314, 2315, 2318, 2324, 2328, 2331, 2336, 2344, 2359, 2360, 2365, 2371, 2372, 2393, 2394, 2398, 2399, 2402, 2418, 2427, 2431, 2437, 2441, 2452, 2455, 2459, 2461, 2462, 2483, 2489, 2494, 2506, 2507, 2508, 2510, 2537, 2541, 2544, 2547, 2548, 2555, 2560, 2587, 2599, 2609, 2622, 2631, 2632, 2638, 2640, 2652, 2671, 2682, 2684, 2704, 2716, 2729, 2737, 2746, 2747, 2756, 2771, 2775, 2776, 2780, 2781, 2783, 2793, 2798, 2817, 2827, 2830, 2835, 2846, 2849, 2863, 2882, 2884, 2893, 2899, 2911, 2920, 2933, 2938, 2942, 2943, 2947, 2956, 2965, 2966, 2967, 2976, 2993, 3005, 3008, 3023, 3025, 3034, 3048, 3054, 3055, 3062, 3063, 3065, 3081, 3086, 3089, 3090, 3091, 3093, 3096, 3099, 3102, 3109, 3110, 3113, 3126, 3127, 3133, 3149, 3155, 3176, 3182, 3206, 3208, 3210, 3211, 3212, 3216, 3226, 3229, 3235, 3253, 3254, 3263, 3264, 3272, 3273, 3290, 3291, 3292, 3299, 3302, 3308, 3319, 3332, 3344, 3352, 3354, 3361, 3368, 3370, 3375, 3378, 3380, 3389, 3392, 3401, 3407, 3411, 3417, 3424, 3427, 3431, 3433, 3436, 3462, 3485, 3499, 3510, 3516, 3518, 3531, 3532, 3541, 3551, 3576, 3601, 3616, 3618, 3623, 3637, 3639, 3641, 3643, 3645, 3659, 3674, 3675, 3690, 3721, 3724, 3736, 3744, 3752, 3760, 3768, 3772, 3780, 3784, 3797, 3802, 3805, 3806, 3807, 3818, 3821, 3830, 3834, 3837, 3854, 3864, 3866, 3874, 3893, 3904, 3925, 3936, 3942, 3947, 3964, 3965, 3968, 3986, 3993, 4011, 4015, 4023, 4040, 4045, 4064, 4070, 4075, 4086, 4107, 4114, 4124, 4126, 4127, 4136, 4158, 4160, 4168, 4170, 4187, 4193, 4215, 4218, 4226, 4234, 4243, 4250, 4252, 4270, 4281, 4284, 4289, 4297, 4312, 4321, 4324, 4339, 4357, 4358, 4370, 4371, 4372, 4380, 4382, 4383, 4387, 4388, 4393, 4395, 4409, 4415, 4418, 4420, 4424, 4425, 4428, 4441, 4445, 4479, 4491, 4501, 4504, 4507, 4509, 4511, 4542, 4551, 4562, 4599, 4601, 4602, 4611, 4614, 4625, 4629, 4663, 4666, 4671, 4689, 4691, 4705, 4714, 4723, 4726, 4732, 4740, 4746, 4747, 4751, 4760, 4774, 4782, 4792, 4793, 4798, 4804, 4805, 4812, 4815, 4830, 4851, 4860, 4874, 4893, 4894, 4905, 4916, 4926, 4946, 4967, 4972, 4976, 4979, 4983, 4985, 4992, 4995, 4999, 5001, 5028, 5039, 5042, 5050, 5053, 5064, 5067, 5072, 5079, 5081, 5085, 5093, 5116, 5119, 5135, 5139, 5159, 5163, 5164, 5172, 5176, 5180, 5182, 5195, 5228, 5244, 5252, 5256, 5262, 5269, 5278, 5288, 5293, 5302, 5307, 5312, 5322, 5326, 5333, 5335, 5336, 5349, 5352, 5369, 5371, 5375, 5389, 5396, 5407, 5409, 5445, 5447, 5448, 5453, 5460, 5463, 5475, 5480, 5489, 5498, 5501, 5511, 5518, 5524, 5525, 5532, 5533, 5536, 5547, 5549, 5556, 5573, 5578, 5587, 5589, 5594, 5596, 5643, 5649, 5657, 5661, 5672, 5689, 5700, 5707, 5715, 5721, 5727, 5732, 5733, 5734, 5745, 5756, 5788, 5789, 5802, 5809, 5818, 5820, 5831, 5841, 5844, 5857, 5875, 5880, 5894, 5899, 5903, 5912, 5922, 5932, 5937, 5939, 5954, 5959, 5960, 5971, 5978, 5985, 5986, 6012, 6015, 6017, 6022, 6039, 6041, 6059, 6068, 6084, 6094, 6109, 6116, 6123, 6129, 6142, 6154, 6167, 6174, 6181, 6185, 6188, 6189, 6192, 6195, 6197, 6203, 6225, 6240, 6276, 6281, 6285, 6286, 6301, 6304, 6319, 6320, 6330, 6333, 6334, 6336, 6337, 6396, 6411, 6412, 6445, 6447, 6449, 6456, 6460, 6461, 6478, 6503, 6504, 6514, 6541, 6547, 6563, 6566, 6574, 6576, 6583, 6584, 6585, 6592, 6593, 6594, 6603, 6606, 6611, 6616, 6643, 6645, 6648, 6655, 6664, 6666, 6667, 6686, 6692, 6696, 6697, 6698, 6708, 6711, 6731, 6751, 6768, 6774, 6797, 6806, 6817, 6850, 6864, 6866, 6869, 6900, 6902, 6906, 6910, 6936, 6937, 6956, 6962, 6972, 6973, 6979, 6984, 6988, 6990, 6991, 6992, 6997, 7028, 7032, 7036, 7042, 7049, 7051, 7055, 7056, 7067, 7073, 7075, 7098, 7099, 7102, 7129, 7131, 7145, 7149, 7174, 7194, 7207, 7213, 7215, 7217, 7224, 7228, 7229, 7232, 7237, 7253, 7257, 7258, 7274, 7291, 7309, 7310, 7312, 7315, 7321, 7340, 7342, 7345, 7350, 7373, 7381, 7382, 7389, 7394, 7398, 7405, 7433, 7440, 7445, 7450, 7453, 7456, 7487, 7492, 7495, 7499, 7500, 7514, 7520, 7523, 7536, 7543, 7545, 7548, 7557, 7608, 7625, 7626, 7662, 7668, 7675, 7692, 7700, 7704, 7733, 7753, 7754, 7755, 7758, 7766, 7773, 7778, 7787, 7788, 7798, 7810, 7815, 7826, 7835, 7843, 7847, 7864, 7872, 7879, 7880, 7883, 7884, 7888, 7889, 7905, 7908, 7920, 7924, 7940, 7944, 7956, 7970, 7980, 7988, 8003, 8014, 8025, 8031, 8058, 8079, 8090, 8099, 8102, 8116, 8121, 8122, 8128, 8136, 8139, 8159, 8160, 8168, 8170, 8173, 8176, 8178, 8185, 8191, 8199, 8216, 8247, 8250, 8251, 8254, 8255, 8267, 8279, 8282, 8293, 8308, 8319, 8322, 8330, 8339, 8355, 8361, 8371, 8374, 8383, 8389, 8397, 8414, 8427, 8428, 8432, 8442, 8461, 8463, 8470, 8488, 8496, 8508, 8511, 8514, 8522, 8529, 8533, 8534, 8552, 8561, 8566, 8573, 8620, 8624, 8625, 8630, 8666, 8681, 8707, 8719, 8724, 8726, 8766, 8767, 8778, 8788, 8790, 8798, 8799, 8801, 8809, 8811, 8815, 8819, 8820, 8860, 8863, 8866, 8873, 8890, 8891, 8897, 8900, 8910, 8923, 8926, 8930, 8933, 8967, 8970, 8975, 8981, 8982, 8983, 8997, 9005, 9014, 9035, 9047, 9048, 9058, 9062, 9070, 9080, 9084, 9086, 9103, 9110, 9120, 9121, 9127, 9141, 9147, 9184, 9192, 9197, 9201, 9214, 9217, 9239, 9243, 9251, 9260, 9276, 9281, 9306, 9313, 9323, 9329, 9335, 9363, 9369, 9371, 9372, 9375, 9382, 9384, 9388, 9392, 9412, 9416, 9421, 9449, 9451, 9453, 9454, 9456, 9463, 9469, 9487, 9488, 9497, 9508, 9516, 9521, 9526, 9529, 9541, 9554, 9556, 9562, 9563, 9567, 9570, 9572, 9573, 9576, 9580, 9589, 9594, 9597, 9605, 9606, 9608, 9610, 9613, 9614, 9615, 9617, 9618, 9626, 9629, 9640, 9645, 9670, 9674, 9679, 9683, 9716, 9721, 9722, 9726, 9748, 9752, 9777, 9792, 9794, 9796, 9803, 9812, 9814, 9818, 9819, 9834, 9851, 9860, 9863, 9876, 9879, 9886, 9895, 9912, 9921, 9936, 9956, 9958, 9963, 9965, 9970, 9978, 9980, 9987, 9996, 10004, 10006, 10027, 10043, 10045, 10047, 10059, 10071, 10074, 10094, 10097, 10102, 10104, 10126, 10134, 10137, 10148, 10149, 10156, 10158, 10159, 10171, 10187, 10193, 10200, 10203, 10204, 10242, 10243, 10250, 10258, 10262, 10264, 10283, 10286, 10289]
--------------------------------------------------
AGE
[188, 426, 453, 467, 643, 1048, 1518, 1724, 1763, 2020, 2858, 2983, 2991, 3028, 3397, 3666, 4036, 4515, 4740, 5218, 5884, 5892, 5987, 6321, 6845, 7078, 7370, 7412, 7735, 7925, 8271, 8386, 8925, 9100, 9119, 9479, 9659, 9822, 9959, 10188]
--------------------------------------------------
HOMEKIDS
[19, 22, 56, 57, 63, 67, 70, 71, 73, 76, 108, 114, 115, 125, 137, 155, 168, 169, 186, 192, 197, 205, 224, 230, 234, 239, 240, 267, 271, 273, 306, 328, 347, 350, 365, 386, 388, 404, 406, 434, 438, 442, 444, 455, 470, 473, 481, 486, 490, 491, 493, 509, 517, 526, 528, 531, 537, 555, 572, 580, 602, 620, 630, 635, 639, 650, 685, 686, 691, 697, 708, 718, 723, 737, 745, 769, 775, 778, 804, 814, 817, 824, 829, 833, 838, 844, 845, 852, 867, 900, 908, 911, 914, 921, 933, 950, 953, 962, 971, 995, 1002, 1010, 1013, 1018, 1023, 1025, 1028, 1035, 1052, 1071, 1077, 1088, 1109, 1111, 1113, 1117, 1125, 1139, 1154, 1170, 1189, 1190, 1193, 1204, 1210, 1231, 1239, 1246, 1248, 1249, 1257, 1272, 1283, 1295, 1306, 1314, 1323, 1326, 1337, 1339, 1344, 1346, 1363, 1382, 1440, 1441, 1451, 1457, 1514, 1523, 1525, 1533, 1542, 1552, 1554, 1560, 1565, 1592, 1595, 1601, 1610, 1621, 1629, 1633, 1635, 1647, 1655, 1665, 1668, 1669, 1670, 1702, 1713, 1717, 1720, 1721, 1739, 1748, 1771, 1772, 1787, 1791, 1820, 1823, 1830, 1836, 1844, 1863, 1872, 1885, 1897, 1907, 1913, 1921, 1933, 1943, 1945, 1953, 1966, 1968, 1971, 1974, 1995, 2006, 2008, 2019, 2020, 2027, 2037, 2055, 2056, 2082, 2084, 2104, 2110, 2111, 2137, 2142, 2143, 2150, 2154, 2170, 2196, 2198, 2201, 2222, 2232, 2238, 2249, 2256, 2269, 2278, 2280, 2309, 2311, 2312, 2314, 2316, 2318, 2321, 2328, 2330, 2344, 2365, 2395, 2402, 2405, 2419, 2425, 2427, 2432, 2433, 2452, 2457, 2461, 2462, 2493, 2495, 2496, 2501, 2505, 2507, 2538, 2555, 2566, 2587, 2594, 2609, 2613, 2624, 2638, 2663, 2704, 2715, 2727, 2730, 2735, 2740, 2784, 2810, 2817, 2823, 2827, 2831, 2835, 2838, 2852, 2859, 2861, 2870, 2874, 2876, 2880, 2883, 2931, 2933, 2943, 2947, 2954, 2961, 2966, 2967, 2972, 2976, 2984, 2993, 3005, 3020, 3031, 3053, 3054, 3055, 3061, 3064, 3072, 3079, 3091, 3099, 3100, 3109, 3127, 3129, 3145, 3148, 3155, 3159, 3204, 3207, 3210, 3211, 3218, 3223, 3224, 3226, 3229, 3230, 3236, 3239, 3245, 3260, 3273, 3292, 3304, 3308, 3319, 3341, 3350, 3359, 3380, 3402, 3407, 3408, 3420, 3431, 3433, 3435, 3451, 3462, 3463, 3466, 3471, 3475, 3481, 3485, 3495, 3498, 3501, 3516, 3532, 3546, 3547, 3550, 3553, 3556, 3604, 3614, 3618, 3623, 3639, 3643, 3650, 3674, 3675, 3680, 3690, 3695, 3703, 3714, 3720, 3721, 3744, 3748, 3752, 3759, 3768, 3782, 3784, 3785, 3789, 3800, 3801, 3805, 3806, 3810, 3814, 3816, 3825, 3830, 3832, 3846, 3858, 3874, 3886, 3889, 3915, 3919, 3920, 3938, 3939, 3947, 3951, 3964, 3968, 3985, 3993, 4022, 4033, 4036, 4052, 4068, 4070, 4073, 4077, 4094, 4099, 4126, 4158, 4163, 4186, 4187, 4188, 4198, 4218, 4221, 4226, 4227, 4264, 4279, 4281, 4312, 4315, 4321, 4324, 4353, 4365, 4370, 4382, 4383, 4387, 4391, 4395, 4409, 4415, 4418, 4441, 4459, 4479, 4490, 4491, 4501, 4507, 4511, 4520, 4524, 4530, 4542, 4547, 4551, 4556, 4572, 4581, 4599, 4606, 4611, 4612, 4629, 4640, 4650, 4663, 4664, 4666, 4674, 4679, 4692, 4712, 4740, 4746, 4751, 4774, 4789, 4791, 4794, 4795, 4801, 4805, 4810, 4822, 4851, 4858, 4873, 4874, 4887, 4890, 4893, 4914, 4938, 4948, 4950, 4961, 4972, 4983, 4987, 4995, 5004, 5017, 5042, 5050, 5079, 5087, 5094, 5102, 5103, 5116, 5133, 5136, 5140, 5147, 5149, 5175, 5180, 5184, 5195, 5203, 5256, 5275, 5283, 5302, 5333, 5335, 5349, 5364, 5375, 5382, 5395, 5409, 5420, 5421, 5446, 5457, 5460, 5462, 5463, 5469, 5472, 5482, 5498, 5514, 5524, 5526, 5545, 5565, 5568, 5584, 5587, 5609, 5628, 5643, 5664, 5672, 5692, 5700, 5707, 5715, 5721, 5722, 5726, 5732, 5737, 5745, 5756, 5773, 5782, 5820, 5838, 5870, 5871, 5873, 5878, 5891, 5896, 5918, 5920, 5938, 5949, 5951, 5963, 5974, 5993, 6022, 6039, 6041, 6044, 6048, 6053, 6056, 6063, 6069, 6080, 6085, 6088, 6109, 6142, 6146, 6173, 6174, 6185, 6190, 6197, 6203, 6225, 6240, 6246, 6253, 6254, 6282, 6304, 6324, 6328, 6333, 6337, 6348, 6360, 6374, 6382, 6392, 6399, 6406, 6432, 6460, 6461, 6469, 6502, 6510, 6513, 6527, 6541, 6555, 6563, 6582, 6583, 6586, 6588, 6594, 6605, 6610, 6612, 6624, 6648, 6651, 6655, 6657, 6663, 6670, 6675, 6681, 6687, 6698, 6699, 6713, 6730, 6744, 6745, 6747, 6756, 6757, 6780, 6842, 6843, 6848, 6850, 6853, 6864, 6866, 6867, 6869, 6870, 6876, 6891, 6902, 6906, 6913, 6919, 6922, 6926, 6929, 6968, 6973, 6979, 6987, 6991, 6992, 6997, 7003, 7028, 7036, 7042, 7049, 7063, 7075, 7076, 7093, 7098, 7099, 7116, 7118, 7131, 7139, 7150, 7171, 7174, 7197, 7213, 7216, 7223, 7224, 7228, 7232, 7248, 7263, 7270, 7296, 7310, 7335, 7342, 7345, 7346, 7350, 7351, 7355, 7374, 7377, 7382, 7397, 7398, 7400, 7414, 7422, 7434, 7435, 7445, 7468, 7469, 7471, 7493, 7501, 7502, 7521, 7553, 7555, 7559, 7625, 7626, 7643, 7651, 7660, 7684, 7692, 7694, 7701, 7704, 7713, 7724, 7728, 7732, 7734, 7735, 7755, 7763, 7773, 7801, 7806, 7809, 7810, 7815, 7822, 7837, 7841, 7847, 7871, 7879, 7883, 7889, 7918, 7922, 7928, 7933, 7941, 7942, 7944, 7956, 7970, 7972, 7978, 7984, 7986, 8000, 8003, 8004, 8025, 8030, 8037, 8041, 8046, 8066, 8072, 8077, 8082, 8083, 8088, 8096, 8116, 8121, 8136, 8160, 8173, 8178, 8189, 8202, 8208, 8216, 8241, 8244, 8251, 8262, 8293, 8299, 8302, 8308, 8328, 8339, 8359, 8361, 8365, 8372, 8374, 8390, 8395, 8399, 8407, 8418, 8419, 8428, 8461, 8463, 8470, 8480, 8481, 8488, 8505, 8508, 8510, 8511, 8522, 8534, 8551, 8568, 8573, 8578, 8583, 8587, 8590, 8604, 8617, 8620, 8628, 8682, 8689, 8695, 8698, 8700, 8702, 8713, 8729, 8730, 8771, 8778, 8786, 8798, 8801, 8802, 8803, 8815, 8819, 8830, 8839, 8842, 8847, 8862, 8863, 8878, 8890, 8891, 8892, 8896, 8910, 8912, 8926, 8930, 8933, 8938, 8951, 8967, 8970, 8971, 8975, 8982, 8983, 9005, 9007, 9009, 9014, 9026, 9039, 9047, 9061, 9062, 9074, 9081, 9082, 9089, 9101, 9110, 9120, 9121, 9137, 9157, 9159, 9160, 9167, 9169, 9170, 9172, 9184, 9192, 9197, 9201, 9210, 9214, 9220, 9231, 9240, 9281, 9308, 9309, 9310, 9311, 9313, 9323, 9329, 9346, 9349, 9363, 9367, 9371, 9378, 9381, 9390, 9409, 9416, 9421, 9424, 9429, 9447, 9451, 9454, 9477, 9488, 9497, 9502, 9508, 9510, 9515, 9516, 9517, 9529, 9541, 9550, 9562, 9570, 9578, 9589, 9604, 9608, 9610, 9615, 9618, 9622, 9623, 9629, 9640, 9655, 9661, 9671, 9674, 9679, 9694, 9696, 9701, 9712, 9724, 9726, 9735, 9737, 9738, 9739, 9743, 9776, 9779, 9788, 9792, 9794, 9805, 9810, 9822, 9839, 9850, 9860, 9863, 9879, 9895, 9902, 9912, 9920, 9923, 9955, 9965, 9966, 9967, 9970, 9980, 9982, 9987, 10003, 10030, 10038, 10047, 10094, 10097, 10131, 10134, 10136, 10183, 10187, 10190, 10196, 10209, 10220, 10225, 10228, 10247, 10262, 10275, 10286]
--------------------------------------------------
YOJ
[]
--------------------------------------------------
TRAVTIME
[260, 272, 313, 657, 763, 1068, 1261, 1432, 1637, 1660, 1721, 1768, 1868, 1906, 1942, 2258, 2316, 2387, 2720, 3177, 3230, 3339, 3342, 3363, 3407, 3412, 3489, 3797, 4070, 4173, 4314, 4679, 4704, 4837, 4918, 4961, 5151, 5175, 5320, 5483, 5657, 5997, 6052, 6085, 6150, 6328, 6359, 6673, 6866, 6910, 6984, 7106, 7131, 7291, 7294, 7352, 7488, 7515, 7642, 7720, 7761, 7906, 8223, 8366, 8530, 8712, 8997, 9065, 9283, 9351, 9390, 9400, 9416, 9472, 9521, 9659, 9668, 10009, 10125, 10200]
--------------------------------------------------
TIF
[33, 57, 145, 243, 260, 264, 313, 372, 420, 443, 567, 582, 675, 737, 761, 820, 864, 923, 943, 967, 982, 1002, 1061, 1101, 1163, 1187, 1375, 1389, 1474, 1512, 1629, 1678, 1728, 1996, 2036, 2088, 2147, 2153, 2272, 2443, 2508, 2598, 2600, 2686, 2712, 2728, 2836, 2861, 2883, 2969, 2979, 2988, 3064, 3106, 3124, 3162, 3170, 3188, 3245, 3290, 3325, 3350, 3365, 3395, 3398, 3429, 3456, 3480, 3612, 3711, 3743, 3838, 3869, 3942, 4023, 4084, 4091, 4101, 4140, 4177, 4198, 4254, 4388, 4423, 4436, 4446, 4525, 4569, 4622, 4628, 4723, 4874, 4903, 4931, 5053, 5185, 5198, 5622, 5703, 5851, 5857, 5875, 5889, 5961, 5994, 6070, 6081, 6100, 6145, 6153, 6159, 6206, 6231, 6263, 6274, 6402, 6457, 6461, 6504, 6532, 6539, 6591, 6617, 6669, 6749, 6756, 6780, 6830, 6850, 6866, 6879, 7015, 7042, 7043, 7052, 7068, 7096, 7196, 7293, 7335, 7355, 7384, 7438, 7517, 7548, 7586, 7655, 7683, 7788, 7843, 7862, 7958, 7963, 8055, 8133, 8160, 8169, 8186, 8266, 8268, 8321, 8322, 8354, 8362, 8435, 8505, 8527, 8558, 8606, 8614, 8657, 8664, 8747, 9061, 9088, 9188, 9210, 9225, 9227, 9345, 9383, 9408, 9466, 9496, 9507, 9550, 9561, 9588, 9898, 9899, 9993, 10005, 10063, 10198]
--------------------------------------------------
CLM_FREQ
[]
--------------------------------------------------
MVR_PTS
[10, 60, 75, 185, 282, 289, 305, 321, 346, 388, 464, 467, 540, 599, 660, 696, 714, 745, 851, 902, 1135, 1147, 1212, 1218, 1222, 1342, 1411, 1519, 1530, 1637, 1669, 1684, 1686, 1724, 1790, 1820, 1869, 1889, 1911, 1931, 1960, 2055, 2079, 2090, 2114, 2237, 2307, 2359, 2437, 2474, 2500, 2510, 2529, 2541, 2604, 2667, 2669, 2682, 2691, 2701, 2855, 2899, 2913, 2972, 3005, 3062, 3085, 3133, 3231, 3260, 3328, 3340, 3351, 3359, 3397, 3442, 3485, 3501, 3522, 3609, 3614, 3631, 3644, 3767, 3782, 3832, 3929, 3935, 3943, 3991, 4127, 4306, 4309, 4328, 4348, 4363, 4412, 4427, 4483, 4507, 4521, 4523, 4545, 4583, 4635, 4740, 4798, 4825, 4929, 4979, 4990, 5018, 5156, 5293, 5364, 5475, 5565, 5660, 5706, 5734, 5854, 5892, 5931, 6013, 6021, 6060, 6127, 6154, 6174, 6321, 6351, 6389, 6459, 6503, 6531, 6535, 6585, 6601, 6603, 6614, 6641, 6814, 6875, 6902, 7005, 7171, 7172, 7298, 7304, 7314, 7342, 7385, 7400, 7453, 7459, 7499, 7572, 7634, 7651, 7748, 7874, 7876, 7877, 7952, 8063, 8087, 8317, 8325, 8565, 8627, 8815, 8834, 8873, 8882, 8896, 8953, 8977, 9034, 9093, 9100, 9128, 9143, 9164, 9171, 9278, 9308, 9388, 9440, 9584, 9640, 9712, 9779, 9780, 9860, 9877, 9881, 9896, 10039, 10083, 10104, 10115, 10175, 10213]
--------------------------------------------------
CAR_AGE
[]
--------------------------------------------------

### 5 - Check inconsistent

In [14]:
# Check summary statistics for Numerical Columns
df.describe().round(2)

,KIDSDRIV,AGE,HOMEKIDS,YOJ,TRAVTIME,TIF,CLM_FREQ,MVR_PTS,CAR_AGE,CLAIM_FLAG
count,10294.00,10294.00,10294.00,9746.00,10294.00,10294.00,10294.00,10294.00,9655.00,10294.00
mean,0.17,44.84,0.72,10.48,33.42,5.33,0.80,1.71,8.30,0.27
std,0.51,8.61,1.12,4.10,15.87,4.11,1.15,2.16,5.71,0.44
min,0.00,16.00,0.00,0.00,5.00,1.00,0.00,0.00,-3.00,0.00
25%,0.00,39.00,0.00,9.00,22.00,1.00,0.00,0.00,1.00,0.00
50%,0.00,45.00,0.00,11.00,33.00,4.00,0.00,1.00,8.00,0.00
75%,0.00,51.00,1.00,13.00,44.00,7.00,2.00,3.00,12.00,1.00
max,4.00,81.00,5.00,23.00,142.00,25.00,5.00,13.00,28.00,1.00

In [15]:
# Check summary statistics for Categorical Columns
df.describe(include= 'object')

,BIRTH,INCOME,PARENT1,HOME_VAL,MSTATUS,GENDER,EDUCATION,OCCUPATION,CAR_USE,BLUEBOOK,CAR_TYPE,RED_CAR,OLDCLAIM,REVOKED,CLM_AMT,URBANICITY
count,10294,9725,10294,9721,10294,10294,10294,9629,10294,10294,10294,10294,10294,10294,10294,10294
unique,6553,8148,2,6334,2,2,5,8,2,2983,6,2,3542,2,2341,2
top,20-Oct-60,$0,No,$0,Yes,z_F,z_High School,z_Blue Collar,Private,"$1,500",z_SUV,no,$0,No,$0,Highly Urban/ Urban
freq,8,794,8955,2903,6185,5540,2950,2288,6506,206,2881,7326,6288,9034,7554,8224

### 6 - Check Unique Values

In [16]:
cat_cols = ['BIRTH', 'PARENT1', 'MSTATUS', 'GENDER',
       'EDUCATION', 'OCCUPATION', 'CAR_USE', 'CAR_TYPE', 'RED_CAR'
       , 'REVOKED', 'URBANICITY']
print(cat_cols)

['BIRTH', 'PARENT1', 'MSTATUS', 'GENDER', 'EDUCATION', 'OCCUPATION', 'CAR_USE', 'CAR_TYPE', 'RED_CAR', 'REVOKED', 'URBANICITY']

In [17]:
for col in cat_cols:
    print(col)
    print(df[col].nunique())
    print(df[col].unique())
    print(df[col].value_counts())

BIRTH
6553
['16-Mar-39' '21-Jan-56' '18-Nov-51' ... '13-Aug-54' '18-Jun-51'
 '27-Feb-47']
BIRTH
20-Oct-60    8
10-Oct-53    7
11-Jan-60    6
07-Feb-48    6
14-May-47    6
            ..
24-Aug-48    1
28-Nov-62    1
07-Nov-71    1
22-Jul-39    1
27-Feb-47    1
Name: count, Length: 6553, dtype: int64
PARENT1
2
['No' 'Yes']
PARENT1
No     8955
Yes    1339
Name: count, dtype: int64
MSTATUS
2
['z_No' 'Yes']
MSTATUS
Yes     6185
z_No    4109
Name: count, dtype: int64
GENDER
2
['M' 'z_F']
GENDER
z_F    5540
M      4754
Name: count, dtype: int64
EDUCATION
5
['PhD' 'z_High School' 'Bachelors' '<High School' 'Masters']
EDUCATION
z_High School    2950
Bachelors        2820
Masters          2078
<High School     1512
PhD               934
Name: count, dtype: int64
OCCUPATION
8
['Professional' 'z_Blue Collar' 'Manager' 'Clerical' 'Doctor' 'Lawyer' nan
 'Home Maker' 'Student']
OCCUPATION
z_Blue Collar    2288
Clerical         1588
Professional     1407
Manager          1257
Lawyer           1031
Student           896
Home Maker        841
Doctor            321
Name: count, dtype: int64
CAR_USE
2
['Private' 'Commercial']
CAR_USE
Private       6506
Commercial    3788
Name: count, dtype: int64
CAR_TYPE
6
['Minivan' 'Van' 'z_SUV' 'Sports Car' 'Panel Truck' 'Pickup']
CAR_TYPE
z_SUV          2881
Minivan        2692
Pickup         1772
Sports Car     1176
Van             920
Panel Truck     853
Name: count, dtype: int64
RED_CAR
2
['yes' 'no']
RED_CAR
no     7326
yes    2968
Name: count, dtype: int64
REVOKED
2
['No' 'Yes']
REVOKED
No     9034
Yes    1260
Name: count, dtype: int64
URBANICITY
2
['Highly Urban/ Urban' 'z_Highly Rural/ Rural']
URBANICITY
Highly Urban/ Urban      8224
z_Highly Rural/ Rural    2070
Name: count, dtype: int64

In [18]:
remove_z_cols = ['MSTATUS', 'GENDER', 'EDUCATION', 'OCCUPATION', 'CAR_TYPE', 'URBANICITY']
remove_z_cols

['MSTATUS', 'GENDER', 'EDUCATION', 'OCCUPATION', 'CAR_TYPE', 'URBANICITY']

In [19]:
def remove_z(x):

    if type(x) == float:
        return x

    elif 'z_' in x:
        return x.replace('z_', '')
    else:
        return x
    
for col in remove_z_cols:

    df[col] = df[col].apply(remove_z)

df[['MSTATUS', 'GENDER', 'EDUCATION', 'OCCUPATION', 'CAR_TYPE', 'URBANICITY']]

,MSTATUS,GENDER,EDUCATION,OCCUPATION,CAR_TYPE,URBANICITY
0,No,M,PhD,Professional,Minivan,Highly Urban/ Urban
1,No,M,High School,Blue Collar,Minivan,Highly Urban/ Urban
2,No,M,Bachelors,Manager,Van,Highly Urban/ Urban
3,Yes,F,High School,Clerical,SUV,Highly Urban/ Urban
4,Yes,M,<High School,Blue Collar,Minivan,Highly Urban/ Urban
...,...,...,...,...,...,...
10289,Yes,M,PhD,Manager,Minivan,Highly Urban/ Urban
10290,Yes,M,Masters,NaN,Panel Truck,Highly Urban/ Urban
10291,Yes,F,<High School,Blue Collar,SUV,Highly Urban/ Urban
10292,Yes,F,Bachelors,Home Maker,Minivan,Highly Urban/ Urban
10293,Yes,F,High School,Clerical,Minivan,Highly Rural/ Rural

In [20]:
df.INCOME

0         $67,349
1         $91,449
2         $52,881
3         $16,039
4             NaN
           ...
10289    $164,669
10290    $107,204
10291     $39,837
10292     $43,445
10293     $53,235
Name: INCOME, Length: 10294, dtype: object

In [21]:
num_cols = ['INCOME', 'HOME_VAL', 'BLUEBOOK', 'OLDCLAIM', 'CLM_AMT']
num_cols

['INCOME', 'HOME_VAL', 'BLUEBOOK', 'OLDCLAIM', 'CLM_AMT']

In [22]:
def clean_num(x):

    if type(x) == float:
        return x
    
    elif ('$' in x) or (',' in x ):
        return x.replace('$', '').replace(',', '')

    else:
        return x

for col in num_cols:

    df[col] = df[col].apply(clean_num).astype('float')

df[['INCOME', 'HOME_VAL', 'BLUEBOOK', 'OLDCLAIM', 'CLM_AMT']]

         INCOME  HOME_VAL  BLUEBOOK  OLDCLAIM  CLM_AMT
0       67349.0       0.0   14230.0    4461.0      0.0
1       91449.0  257252.0   14940.0       0.0      0.0
2       52881.0       0.0   21970.0       0.0      0.0
3       16039.0  124191.0    4010.0   38690.0      0.0
4           NaN  306251.0   15440.0       0.0      0.0
...         ...       ...       ...       ...      ...
10289  164669.0  386273.0   13270.0       0.0      0.0
10290  107204.0  332591.0   24490.0       0.0      0.0
10291   39837.0  170611.0   13820.0       0.0      0.0
10292   43445.0  149248.0   22550.0       0.0      0.0
10293   53235.0  197017.0   19400.0       0.0      0.0

[10294 rows x 5 columns]

In [23]:
df.car_age = df['CAR_AGE'].abs()
df['CAR_AGE']

0        18.0
1         1.0
2        10.0
3        10.0
4         6.0
         ...
10289    17.0
10290     1.0
10291     1.0
10292    11.0
10293     9.0
Name: CAR_AGE, Length: 10294, dtype: float64

In [24]:
df.drop(['BIRTH','CLM_FREQ','CLM_AMT'], axis= 1, inplace= True)

In [25]:
df.duplicated().sum()

0

### Feature Engineering

In [26]:
df['TIF'].value_counts()

TIF
1     3169
6     1707
4     1616
10     948
7      781
3      531
13     355
11     299
9      298
17     126
14      92
8       83
5       70
12      55
16      50
15      40
18      26
21      13
20      12
19      11
2        6
22       3
25       3
Name: count, dtype: int64

In [27]:
# Create a new column named loyal_cust based on years with the company
def loyal_cust(x):

    if x < 8:
        return 'New Customer'
    
    elif x < 15:
        return 'Loyal Customer'
    
    else:
        return 'Very Loyal Customer'
    
df['TIF'].apply(loyal_cust).value_counts()

TIF
New Customer           7880
Loyal Customer         2130
Very Loyal Customer     284
Name: count, dtype: int64

In [28]:
df['customer_loyalty'] = df['TIF'].apply(loyal_cust)
df['customer_loyalty']

0             Loyal Customer
1               New Customer
2               New Customer
3               New Customer
4               New Customer
                ...
10289    Very Loyal Customer
10290           New Customer
10291           New Customer
10292           New Customer
10293           New Customer
Name: customer_loyalty, Length: 10294, dtype: object

### Save cleaned dataframe for later use in streamlit python file

In [29]:
import os 
os.chdir('C:/Users/mostafa/New folder')

In [30]:
df.to_csv('cleaned_df.csv')

# Data Preprocessing

# Data Preprocessing Steps for Machine Learning :

* 1- Split Data into Input Features and Target Column

* 2- Split Data into Train & Test

* 3- Numerical Cols : Impute Missing --> Scaling

* 4- Categorical Cols : Impute Missing --> Encoding

* 5- Handle Imbalance

### 1- Split Data into input Features and Target Feature

In [31]:
x = df.drop('CLAIM_FLAG', axis= 1)
y = df['CLAIM_FLAG']

In [32]:
df['CLAIM_FLAG'].value_counts()

CLAIM_FLAG
0    7554
1    2740
Name: count, dtype: int64

## Numerical pipeline

In [33]:
num_cols = x.select_dtypes(include= 'number').columns
num_cols

Index(['KIDSDRIV', 'AGE', 'HOMEKIDS', 'YOJ', 'INCOME', 'HOME_VAL', 'TRAVTIME',
       'BLUEBOOK', 'TIF', 'OLDCLAIM', 'MVR_PTS', 'CAR_AGE'],
      dtype='object')

In [34]:
from sklearn.pipeline import Pipeline
from sklearn.impute import KNNImputer
from sklearn.preprocessing import RobustScaler

knn_imputer = KNNImputer()
rc = RobustScaler()

num_pipeline = Pipeline([('Knn', knn_imputer), ('Scaling', rc)])
num_pipeline

Pipeline(steps=[('Knn', KNNImputer()), ('Scaling', RobustScaler())])

## Categorical Pipelines

### Occupation Column Pipeline (Imputation --> Encoding)

In [35]:
from sklearn.impute import SimpleImputer
from category_encoders import BinaryEncoder

be = BinaryEncoder()
imputer = SimpleImputer(strategy= 'constant', fill_value= 'Other')

occupation_pipeline = Pipeline([('Cat Impute Pipeline', imputer), ('BE', be)])
occupation_pipeline

Pipeline(steps=[('Cat Impute Pipeline',
                 SimpleImputer(fill_value='Other', strategy='constant')),
                ('BE', BinaryEncoder())])

### OHE Pipeline

In [36]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop= 'first', sparse_output= False)

ohe_pipeline = Pipeline([('OHE Pipeline', ohe)])
ohe_pipeline

Pipeline(steps=[('OHE Pipeline',
                 OneHotEncoder(drop='first', sparse_output=False))])

### Ordinal Pipeline

In [37]:
from sklearn.preprocessing import OrdinalEncoder

ord = OrdinalEncoder(categories= [['<High School', 'High School', 'Bachelors', 'Masters', 'PhD']])

ord_pipeline = Pipeline([('Ordinal Pipeline', ord)])
ord_pipeline

Pipeline(steps=[('Ordinal Pipeline',
                 OrdinalEncoder(categories=[['<High School', 'High School',
                                             'Bachelors', 'Masters',
                                             'PhD']]))])

### Assign each column to the corresponding Pipeline

In [38]:
ohe_cols = x.select_dtypes(include= ['object']).columns.drop(['EDUCATION', 'OCCUPATION'])
ohe_cols

Index(['PARENT1', 'MSTATUS', 'GENDER', 'CAR_USE', 'CAR_TYPE', 'RED_CAR',
       'REVOKED', 'URBANICITY', 'customer_loyalty'],
      dtype='object')

In [39]:
from sklearn.compose import ColumnTransformer

Preprocessing = ColumnTransformer(transformers= [ ('Numerical', num_pipeline, num_cols),
                                                  ('Occupation Categorical', occupation_pipeline, ['OCCUPATION']),
                                                  ('OHE', ohe_pipeline, ohe_cols),
                                                  ('Ordinal', ord_pipeline, ['EDUCATION'])] )
Preprocessing

ColumnTransformer(transformers=[('Numerical',
                                 Pipeline(steps=[('Knn', KNNImputer()),
                                                 ('Scaling', RobustScaler())]),
                                 Index(['KIDSDRIV', 'AGE', 'HOMEKIDS', 'YOJ', 'INCOME', 'HOME_VAL', 'TRAVTIME',
       'BLUEBOOK', 'TIF', 'OLDCLAIM', 'MVR_PTS', 'CAR_AGE'],
      dtype='object')),
                                ('Occupation Categorical',
                                 Pipeline(steps=[('Cat Impute Pipeline',
                                                  SimpleImputer(fill_value='Other',
                                                                strate...
                                 Pipeline(steps=[('OHE Pipeline',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False))]),
                                 Index(['PARENT1', 'MSTATUS', 'GENDER', 'CAR_USE', 'CAR_TYPE', 'RED_CAR',
       'REVOKED', 'URBANICITY', 'customer_loyalty'],
      dtype='object')),
                                ('Ordinal',
                                 Pipeline(steps=[('Ordinal Pipeline',
                                                  OrdinalEncoder(categories=[['<High '
                                                                              'School',
                                                                              'High '
                                                                              'School',
                                                                              'Bachelors',
                                                                              'Masters',
                                                                              'PhD']]))]),
                                 ['EDUCATION'])])

In [40]:
# ! pip install lightgbm

In [41]:
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import cross_validate

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier

models = [
    ('Logistic Regression', LogisticRegression(random_state= 42)),
    ('KNN', KNeighborsClassifier()),
    ('Naive Bayes', GaussianNB()),
    ('Decision Tree', DecisionTreeClassifier(random_state= 42)),
    ('Random Forest', RandomForestClassifier(random_state= 42)),
    ('XGBoost', XGBClassifier()),
    ('CatBoost', CatBoostClassifier()),
    ('LightGBM', LGBMClassifier())
]

for model in models:

    model_pipeline = Pipeline(steps= [ ('Preprocessing', Preprocessing),
                                       ('smote', SMOTE()),
                                       ('Model', model[1])])
    
    result = cross_validate(model_pipeline, x, y, scoring= 'f1', cv= 5, return_train_score= True, n_jobs= -1)

    print(model[0])
    print('Train Score :', round(result['train_score'].mean() * 100, 2))
    print('Test Score :', round(result['test_score'].mean() * 100, 2))
    print('-' * 50)

Logistic Regression
Train Score : 59.31
Test Score : 58.8
--------------------------------------------------
KNN
Train Score : 69.19
Test Score : 50.13
--------------------------------------------------
Naive Bayes
Train Score : 55.92
Test Score : 55.67
--------------------------------------------------
Decision Tree
Train Score : 100.0
Test Score : 45.54
--------------------------------------------------
Random Forest
Train Score : 100.0
Test Score : 54.88
--------------------------------------------------
XGBoost
Train Score : 92.06
Test Score : 53.47
--------------------------------------------------
CatBoost
Train Score : 79.58
Test Score : 56.53
--------------------------------------------------
LightGBM
Train Score : 75.52
Test Score : 55.58
--------------------------------------------------

In [42]:
from lightgbm import LGBMClassifier
from sklearn.model_selection import RandomizedSearchCV

model_pipeline = Pipeline(
    steps=[
        ('Preprocessing', Preprocessing),
        ('smote', SMOTE()),
        ('Model', LGBMClassifier(
            random_state=42,
            verbose=-1
        ))
    ]
)

params = {
    'Model__n_estimators': [100, 200, 300],
    'Model__learning_rate': [0.01, 0.03, 0.05, 0.1],
    'Model__max_depth': [3, 5, 7, 10],
    'Model__num_leaves': [15, 31, 63]
}

random_search = RandomizedSearchCV(
    estimator=model_pipeline,
    param_distributions=params,
    n_iter=13,
    scoring='f1',
    cv=5,
    random_state=42,
    n_jobs=-1,
    return_train_score=True
)

random_search.fit(x, y)

print(random_search.best_score_)
print(random_search.best_params_)

0.5810108336892541
{'Model__num_leaves': 31, 'Model__n_estimators': 100, 'Model__max_depth': 5, 'Model__learning_rate': 0.05}

In [43]:
result['fit_time']

array([4.25163341, 7.3694067 , 4.22163033, 4.19463134, 2.44598436])

In [44]:
random_search.best_score_

0.5810108336892541

In [45]:
random_search.best_params_

{'Model__num_leaves': 31,
 'Model__n_estimators': 100,
 'Model__max_depth': 5,
 'Model__learning_rate': 0.05}

In [46]:
random_search.cv_results_['mean_train_score']

array([0.65160267, 0.60435144, 0.64132285, 0.80184105, 0.67186249,
       0.59869754, 0.79198087, 0.71016651, 0.62484053, 0.58398263,
       0.64650657, 0.62130856, 0.73782499])

In [47]:
random_search.cv_results_['mean_test_score']

array([0.5748608 , 0.57066608, 0.58101083, 0.55394142, 0.56928649,
       0.57740935, 0.55011646, 0.57404713, 0.57734812, 0.56888877,
       0.57787178, 0.5803896 , 0.56354187])

In [48]:
from lightgbm import LGBMClassifier

final_pipeline = Pipeline(
    steps=[
        ('Preprocessing', Preprocessing),
        ('smote', SMOTE()),
        ('Model', LGBMClassifier(num_leaves=15,n_estimators=300,max_depth=3,learning_rate=0.05,random_state=42,verbose=-1))]
)

final_pipeline.fit(x, y)

Pipeline(steps=[('Preprocessing',
                 ColumnTransformer(transformers=[('Numerical',
                                                  Pipeline(steps=[('Knn',
                                                                   KNNImputer()),
                                                                  ('Scaling',
                                                                   RobustScaler())]),
                                                  Index(['KIDSDRIV', 'AGE', 'HOMEKIDS', 'YOJ', 'INCOME', 'HOME_VAL', 'TRAVTIME',
       'BLUEBOOK', 'TIF', 'OLDCLAIM', 'MVR_PTS', 'CAR_AGE'],
      dtype='object')),
                                                 ('Occupation Categorical',
                                                  Pipeline(steps=[('Cat Impute '
                                                                   'Pipeline',
                                                                   Simp...
       'REVOKED', 'URBANICITY', 'customer_loyalty'],
      dtype='object')),
                                                 ('Ordinal',
                                                  Pipeline(steps=[('Ordinal '
                                                                   'Pipeline',
                                                                   OrdinalEncoder(categories=[['<High '
                                                                                               'School',
                                                                                               'High '
                                                                                               'School',
                                                                                               'Bachelors',
                                                                                               'Masters',
                                                                                               'PhD']]))]),
                                                  ['EDUCATION'])])),
                ('smote', SMOTE()),
                ('Model',
                 LGBMClassifier(learning_rate=0.05, max_depth=3,
                                n_estimators=300, num_leaves=15,
                                random_state=42, verbose=-1))])

In [49]:
final_pipeline.predict(x.head(1))

array([0], dtype=int64)

In [50]:
final_pipeline.predict(x.head(1))[0]

0

In [51]:
# ! pip install joblib

In [52]:
import joblib

joblib.dump(final_pipeline, 'lightgbm.pkl')

['lightgbm.pkl']

### Deployment

In [53]:
import streamlit as st

In [54]:
df.columns

Index(['KIDSDRIV', 'AGE', 'HOMEKIDS', 'YOJ', 'INCOME', 'PARENT1', 'HOME_VAL',
       'MSTATUS', 'GENDER', 'EDUCATION', 'OCCUPATION', 'TRAVTIME', 'CAR_USE',
       'BLUEBOOK', 'TIF', 'CAR_TYPE', 'RED_CAR', 'OLDCLAIM', 'REVOKED',
       'MVR_PTS', 'CAR_AGE', 'CLAIM_FLAG', 'URBANICITY', 'customer_loyalty'],
      dtype='object')

In [55]:
%%writefile car_insurance_deploymeny.py

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.impute import KNNImputer
from sklearn.preprocessing import RobustScaler
from sklearn.impute import SimpleImputer
from category_encoders import BinaryEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.compose import ColumnTransformer
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import cross_validate
from lightgbm import LGBMClassifier
import joblib

st.set_page_config(layout= 'wide', page_title='Car Insurance Deployment')

st.image('https://thumbs.dreamstime.com/b/car-insurance-logo-auto-protection-safety-secure-shield-stock-photo-generative-ai-illustration-representing-vehicle-security-369131383.jpg?w=992')

df = pd.read_csv('cleaned_df.csv', index_col= 0)
# st.dataframe(df)

kidsdriv = st.selectbox('PLease provid number of driving kids', df['KIDSDRIV'].unique())
age = st.sidebar.slider('Enter your Age', 16, 81)
homekids = st.selectbox('PLease provid total number of kids', df['HOMEKIDS'].unique())
yoj = st.sidebar.slider('Please provide number of years on job', min_value= int(df['YOJ'].min()), max_value= int(df['YOJ'].max()), step= 1)
income = st.number_input('Please provide your income', min_value= df['INCOME'].min(), max_value= df['INCOME'].max())
parent1 = st.selectbox('PLease select whether you are single parent or not', df['PARENT1'].unique())
home_val = st.number_input('Please provide your home value', min_value= df['HOME_VAL'].min(), max_value= df['HOME_VAL'].max())
mstatus = st.sidebar.radio('Marital Status', df['MSTATUS'].unique())
gender = st.sidebar.radio('Gender', df['GENDER'].unique())
education = st.selectbox('Please enter your educational background', df['EDUCATION'].unique())
occupation = st.selectbox('Please enter your Occupation', df['OCCUPATION'].unique())
travtime = st.sidebar.slider('Please enter your travel time in minutes', min_value= df['TRAVTIME'].min(), max_value= df['TRAVTIME'].max(), step= 1)
car_use = st.selectbox('PLease provid your car usage', df['CAR_USE'].unique())
bluebook = st.number_input('Please provide your car value', min_value= df['BLUEBOOK'].min(), max_value= df['BLUEBOOK'].max())
tif = st.sidebar.slider('Loyalty years', min_value= df['TIF'].min(), max_value= df['TIF'].max(), step= 1)
car_type = st.selectbox('PLease provid your car type', df['CAR_TYPE'].unique())
red_car = st.selectbox('Red car or Not', df['RED_CAR'].unique())
oldclaim = st.number_input('Please provide your old claim amount', min_value= df['OLDCLAIM'].min(), max_value= df['OLDCLAIM'].max())
#clm_freq = st.sidebar.slider('Please provide number of previous claims', min_value= df['CLM_FREQ'].min(), max_value= df['CLM_FREQ'].max(), step= 1)
revoked = st.selectbox('License Revoked within 7 years', df['REVOKED'].unique())
mvr_pts = st.sidebar.slider('Please provide vechile record points', min_value= df['MVR_PTS'].min(), max_value= df['MVR_PTS'].max(), step= 1)
#clm_amt = st.number_input('Please provide your total claims amount', min_value= df['CLM_AMT'].min(), max_value= df['CLM_AMT'].max())
car_age = st.sidebar.slider('Please enter your car age', min_value= int(df['CAR_AGE'].min()), max_value= int(df['CAR_AGE'].max()), step= 1)
urbanicity = st.selectbox('Urbanicity', df['URBANICITY'].unique())
customer_loyalty = st.selectbox('Customer Loyalty', df['customer_loyalty'].unique())

# Import Model pkl file
model = joblib.load('lightgbm.pkl')

new_data = pd.DataFrame(columns= df.columns.drop('CLAIM_FLAG'), 
                        data= [[kidsdriv, age, homekids, yoj, income, parent1, home_val,
                            mstatus, gender, education, occupation, travtime, car_use,
                            bluebook, tif, car_type, red_car, oldclaim,
                            revoked, mvr_pts, car_age, urbanicity,
                            customer_loyalty]])

if st.button('Predict'):

    result = model.predict(new_data)[0]

    if result == 0:
        st.write('Desired Customer')

    else:
        st.write('Undesired Customer')

Overwriting car_insurance_deploymeny.py

In [56]:
! streamlit run car_insurance_deploymeny.py

^C

# Steps to make your web application Public

##### After creating requirements.txt file:
##### 1- Create new repository on GitHub
##### 2- Upload python file, requirements.txt file, pkl file, and any dataset or photo you used in the python file
##### 3- From streamlit.io page sign in using Github account
##### 4- Select new, then put repository name and python file name
##### 5- Click on Deploy and wait for web page to get ready
##### 6- Once it's loaded, that means your web application is public now and you can share the link with others

In [65]:
# This command will search in current folder and detect any python file, then get versions of all libraries in that file
! pipreqs ./

INFO: Not scanning for jupyter notebooks.
WARNING: Import named "category_encoders" not found locally. Trying to resolve it at the PyPI server.
WARNING: Import named "category_encoders" was resolved to "category-encoders:2.9.0" package (https://pypi.org/project/category-encoders/).
Please, verify manually the final list of requirements.txt to avoid possible dependency confusions.
WARNING: Import named "lightgbm" not found locally. Trying to resolve it at the PyPI server.
WARNING: Import named "lightgbm" was resolved to "lightgbm:4.6.0" package (https://pypi.org/project/lightgbm/).
Please, verify manually the final list of requirements.txt to avoid possible dependency confusions.
WARNING: Import named "numpy" not found locally. Trying to resolve it at the PyPI server.
WARNING: Import named "numpy" was resolved to "numpy:2.5.0" package (https://pypi.org/project/numpy/).
Please, verify manually the final list of requirements.txt to avoid possible dependency confusions.
WARNING: Import named "pandas" not found locally. Trying to resolve it at the PyPI server.
WARNING: Import named "pandas" was resolved to "pandas:3.0.3" package (https://pypi.org/project/pandas/).
Please, verify manually the final list of requirements.txt to avoid possible dependency confusions.
WARNING: Import named "scikit_learn" not found locally. Trying to resolve it at the PyPI server.
WARNING: Import named "scikit_learn" was resolved to "scikit-learn:1.9.0" package (https://pypi.org/project/scikit-learn/).
Please, verify manually the final list of requirements.txt to avoid possible dependency confusions.
INFO: Successfully saved requirements file in ./requirements.txt